title: "Bernard Joseph Oyakhilome – Data Analyst / BI Analyst"
description: >
  Data Analyst | Retail • Fintech • Healthcare | Driving Business Growth & Efficiency Through SQL, Power BI, Excel, Data Analysis & KPI-Driven Insights

remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme
